apiVersion: v1
kind: Secret
metadata:
  name: reserve-secret
type: Opaque
data:
  POSTGRES_PASSWORD: c2VjcmV0cGFzc3dvcmQ=
  SECRET_KEY: cmVzZXJ2ZV9zdXBlcl9zZWNyZXRfZGV2X2tleV9jaGFuZ2VfaW5fcHJvZHVjdGlvbl85ODc2NTQzMjE=
