"""create_initial_models

Revision ID: ca39d5fea89e
Revises: 
Create Date: 2026-10-04 12:24:17.385171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca39d5fea89e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('DONOR', 'NGO', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('donors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('donor_type', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_donors_name'), 'donors', ['name'], unique=False)
    op.create_table('ngos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('total_capacity_meals', sa.Integer(), nullable=False),
    sa.Column('current_capacity_meals', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_ngos_name'), 'ngos', ['name'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=False),
    sa.Column('forecast_for_date', sa.DateTime(), nullable=False),
    sa.Column('predicted_quantity_meals', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_donor_id'), 'forecasts', ['donor_id'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_for_date'), 'forecasts', ['forecast_for_date'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('food_type', sa.Enum('COOKED_MEALS', 'BAKERY', 'PRODUCE', 'DAIRY', 'PACKAGED', 'BEVERAGES', name='foodtype'), nullable=False),
    sa.Column('quantity_meals', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pickup_address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('prep_time', sa.DateTime(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ALLOCATED', 'PICKED_UP', 'EXPIRED', name='listingstatus'), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('dietary_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_donor_id'), 'listings', ['donor_id'], unique=False)
    op.create_index(op.f('ix_listings_expiry_time'), 'listings', ['expiry_time'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('ngo_id', sa.String(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_listing_id'), 'allocations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_allocations_ngo_id'), 'allocations', ['ngo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocations_ngo_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_listing_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_expiry_time'), table_name='listings')
    op.drop_index(op.f('ix_listings_donor_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_forecasts_forecast_for_date'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_donor_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_ngos_name'), table_name='ngos')
    op.drop_table('ngos')
    op.drop_index(op.f('ix_donors_name'), table_name='donors')
    op.drop_table('donors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
